# Generated by Django 2.2 on 2019-11-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guantapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
