# Generated by Django 2.2 on 2019-11-28 23:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guantapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='valor_calificacion',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Nombre de producto inválido', regex='[1-5]')]),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Nombre de categoría inválido', regex='[A-Za-z\\s]{4,50}')]),
        ),
        migrations.AlterField(
            model_name='lineaorden',
            name='cantidad',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Nombre de producto inválido', regex='[A-Za-z0-9\\s]{4,50}')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nit',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator(message='NIT inválido', regex='[0-9]{14}')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator(message='Teléfono inválido', regex='[267][0-9]{7}')]),
        ),
    ]
