# Generated by Django 2.2 on 2019-11-28 23:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guantapp', '0002_auto_20191128_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nit',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='NIT inválido', regex='[0-9]{14}')]),
        ),
    ]
