# Generated by Django 2.2 on 2019-11-29 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guantapp', '0004_auto_20191128_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='valor_calificacion',
            field=models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(message='Nombre de producto inválido', regex='[1-5]')]),
        ),
    ]
