# Generated by Django 2.2 on 2019-11-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guantapp', '0006_auto_20191128_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
