# Generated by Django 2.2 on 2019-11-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guantapp', '0007_auto_20191128_1931'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.UniqueConstraint(fields=('producto', 'user_profile'), name='unique_calificacion'),
        ),
    ]
