# Generated by Django 2.2 on 2019-11-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guantapp', '0008_auto_20191128_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nrc',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
