# Generated by Django 2.2 on 2019-11-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guantapp', '0009_auto_20191128_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nrc',
            field=models.CharField(max_length=2),
        ),
    ]
